version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "MySql1112!"
      MYSQL_DATABASE: "santa-secret"
    ports:
      - "3306:3306"
    volumes:
      - ./tmp:/var/lib/mysql
    networks:
      - mysql-compose-network
networks:
  mysql-compose-network:
    driver: bridge